### ISSUE TITLE
PollSubmission redesign

### ISSUE THREAD

**Issue by ilyayudovin** [which-ecosystem/which#88]

**Comment by ilyayudovin** [comment]
![tele1](https://user-images.githubusercontent.com/46264063/90390337-d5ccbb00-e093-11ea-9c9e-2493fc719790.jpg)
![tele2](https://user-images.githubusercontent.com/46264063/90390347-d8c7ab80-e093-11ea-812d-ec3e123f7763.jpg)

**Comment by eug-vs** [comment]
Solved in #101 #102 #103
